### ISSUE TITLE
[website] Code links broken

### ISSUE THREAD

**Issue by shayanb** [IC3Hydra/Hydra#3]
This is not related to the repo but the website `thehydra.io`.

The links to the codes [2],[3] and [4] are broken in section `Deployed bounties (Ethereum mainnet)`. 

Broken Links: 
- https://github.com/IC3Hydra/Hydra/blob/master/examples/ERC20/nonviper/ERC20_serpent.se
- https://github.com/IC3Hydra/Hydra/blob/master/examples/ERC20/nonviper/ERC20_solidity_1.sol
- https://github.com/IC3Hydra/Hydra/blob/master/examples/ERC20/nonviper/ERC20_solidity_2.sol

**Comment by lorenzb** [comment]
Thanks @shayanb, should be fixed.
